on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: ü§ñ
    steps:
      - name: ü§ñ PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.MODEL: groq/llama-3.1-70b-versatile
          CONFIG.MODEL_TURBO: groq/llama-3.1-70b-versatile
          CONFIG.FALLBACK_MODELS: "groq/llama-3.1-8b-instant"
          CONFIG.CUSTOM_MODEL_MAX_TOKENS: 14400
          GROQ.KEY: ${{ secrets.GROQ_KEY }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: >-
            Chuy·ªÉn c√¢u tr·∫£ l·ªùi sang ti·∫øng Vi·ªát.
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: >-
            Ti√™u ƒë·ªÅ ph·∫£i bao g·ªìm m·ªôt ti·ªÅn t·ªë t·ª´ m·∫´u commitlint nh∆∞ feat:, chore:, test:, fix:, ci:, ho·∫∑c docs:... 
            Ti√™u ƒë·ªÅ ph·∫£i l√† ti·∫øng anh ng·∫Øn g·ªçn v√† vi·∫øt th∆∞·ªùng to√†n b·ªô c√¢u.
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: >-
            Chuy·ªÉn c√¢u tr·∫£ l·ªùi sang ti·∫øng Vi·ªát.
          PR_DESCRIPTION.GENERATE_AI_TITLE: true
